# Generated by Django 3.0.6 on 2020-05-19 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoofyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='max. 250 znaków', max_length=250, verbose_name='Treść')),
                ('city', models.CharField(default='Cała Polska', help_text='Podaj swoje miasto, ułatwi to życie innym', max_length=64, verbose_name='Miasto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa Twojej firmy')),
                ('category', models.IntegerField(choices=[(1, 'hodowla'), (2, 'weterynarz'), (3, 'psi fryzjer'), (4, 'sklep zoologiczny'), (5, 'szkolenie psów'), (6, 'opieka nad psem'), (7, 'psi behawiorysta')], help_text='Wybierz jedną z kategorii', verbose_name='Kategoria')),
                ('description', models.CharField(help_text='max. 128 znaków', max_length=255, null=True, verbose_name='Dodatkowy opis')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='Adres')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='e-mail')),
                ('homepage', models.URLField(null=True, verbose_name='Twoja strona www')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Temat')),
                ('content', models.TextField(verbose_name='Wiadomość')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='Komentarz')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofy.WoofyPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł ogłoszenia')),
                ('content', models.CharField(help_text='Opis, który będzie widoczny na stronie głównej', max_length=140, verbose_name='Krótki opis')),
                ('all_details', models.TextField(verbose_name='Szczegóły')),
                ('city', models.CharField(default='Cała Polska', help_text='Podaj swoje miasto, ułatwi to życie innym', max_length=64, verbose_name='Miasto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
