# Generated by Django 2.2.5 on 2019-09-24 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoofyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='max. 140 znaków', max_length=140, verbose_name='Treść')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(default='Cała Polska', help_text='Podaj swoje miasto ułatwi to życie innym', max_length=64, verbose_name='Miasto')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Nazwa Twojej firmy')),
                ('category', models.IntegerField(choices=[(1, 'Hodowla'), (2, 'Weterynarz'), (3, 'Psi fryzjer'), (4, 'Sklep zoologiczny'), (5, 'Szkolenie psów'), (6, 'Opieka nad psem'), (7, 'Psi behawiorysta')], help_text='Wybierz jedną z kategorii', verbose_name='Kategoria')),
                ('description', models.CharField(help_text='max. 128 znaków', max_length=128, null=True, verbose_name='Dodatkowy opis')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('homepage', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
