# Generated by Django 2.2.5 on 2019-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='homepage',
            field=models.URLField(null=True, verbose_name='Twoja strona www'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefon'),
        ),
    ]
