# Generated by Django 2.2.5 on 2019-09-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.CharField(default='Cała Polska', help_text='Podaj swoje miasto, ułatwi to życie innym', max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='woofypost',
            name='city',
            field=models.CharField(default='Cała Polska', help_text='Podaj swoje miasto, ułatwi to życie innym', max_length=64, verbose_name='Miasto'),
        ),
    ]
