# Generated by Django 2.2.5 on 2019-09-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0006_auto_20190925_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofy.WoofyPost'),
        ),
    ]
