# Generated by Django 2.2.5 on 2019-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='Temat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(verbose_name='Wiadomość'),
        ),
    ]
