# Generated by Django 2.2.5 on 2019-09-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0010_auto_20190925_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_content',
            new_name='content',
        ),
    ]
