# Generated by Django 2.2.5 on 2019-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0011_auto_20190925_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='all_details',
            field=models.TextField(default='szczegóły całe ogłoszenia', verbose_name='Szczegóły'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(help_text='Opis, który będzie widoczny na stronie głównej', max_length=140, verbose_name='Krótki opis'),
        ),
    ]
