# Generated by Django 2.2.5 on 2019-09-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0012_auto_20190926_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woofypost',
            name='image',
        ),
    ]
