# Generated by Django 2.2.5 on 2019-09-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0013_remove_woofypost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='woofypost',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
