# Generated by Django 2.2.5 on 2019-09-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0014_woofypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woofypost',
            name='image',
        ),
    ]
