# Generated by Django 2.2.5 on 2019-09-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0015_remove_woofypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='description',
            field=models.CharField(help_text='max. 128 znaków', max_length=255, null=True, verbose_name='Dodatkowy opis'),
        ),
        migrations.AlterField(
            model_name='woofypost',
            name='content',
            field=models.CharField(help_text='max. 250 znaków', max_length=250, verbose_name='Treść'),
        ),
    ]
