# Generated by Django 2.2.5 on 2019-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0017_woofypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woofypost',
            name='image',
            field=models.ImageField(upload_to='post_image'),
        ),
    ]
