# Generated by Django 2.2.5 on 2019-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofy', '0019_auto_20190927_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woofypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
